"""Domain package."""

from .models import (
    Ability,
    AbilityCategory,
    Character,
    ChatContact,
    ChatMessage,
    ChatThread,
    ChoiceOption,
    ClassDefinition,
    EquipmentState,
    EquipmentSlot,
    FriendRequest,
    InventoryState,
    ItemInstance,
    ItemTemplate,
    ItemType,
    MessageSeverity,
    Objective,
    QuestInstance,
    QuestStatus,
    QuestTemplate,
    Rarity,
    SystemMessage,
)
from .events import EventLogEntry
from .errors import DomainError, EquipError, PermissionError, QuestError
from .rules import ClassPerLevelBonus, StatPointRule, XPCurveExponential
from .services import (
    can_equip_item,
    choose_message_option,
    compute_level_from_xp,
    derive_equipment_granted_abilities,
    derive_equipment_stat_mods,
    ensure_quest_not_duplicated,
    equip_item,
    grant_xp_and_level,
)

__all__ = [
    "Ability",
    "AbilityCategory",
    "Character",
    "ChatContact",
    "ChatMessage",
    "ChatThread",
    "ChoiceOption",
    "ClassDefinition",
    "EquipmentState",
    "EquipmentSlot",
    "EventLogEntry",
    "FriendRequest",
    "InventoryState",
    "ItemInstance",
    "ItemTemplate",
    "ItemType",
    "MessageSeverity",
    "Objective",
    "QuestInstance",
    "QuestStatus",
    "QuestTemplate",
    "Rarity",
    "SystemMessage",
    "DomainError",
    "EquipError",
    "PermissionError",
    "QuestError",
    "ClassPerLevelBonus",
    "StatPointRule",
    "XPCurveExponential",
    "can_equip_item",
    "choose_message_option",
    "compute_level_from_xp",
    "derive_equipment_granted_abilities",
    "derive_equipment_stat_mods",
    "ensure_quest_not_duplicated",
    "equip_item",
    "grant_xp_and_level",
]
